# Copyright (c) 2022 NVIDIA CORPORATION.  All rights reserved.

[mypy]
# make command line output easier to read
pretty = True

# do not produce errors for imported code
# (only produce errors for the explicitly listed files)
follow_imports = silent

# follow imports to discover type stubs
follow_imports_for_stubs = True

[mypy-open3d.*]
# open3d imports some broken tensorflow libs internally - prevent them from being analyzed
follow_imports = skip

[mypy-DracoPy.*]
ignore_missing_imports = True
